export interface Product {
  productId: string;
  productName: string;
  productCode: string;
  weight: string;
  MRP: string;
  unitPrice: number;
  Segment: string;
  category?: string;
  ProductFamily?: string;
  regularImageURL: string;
  gifImageURL?: string;
  zipperImageURL?: string;
  zipperGifImageURL?: string;
  mediaType?: 'image' | 'video';
  gstPercentage: number;
  boxBunch: number;
  patti: number;
  packet: number;
  newItem: boolean;
  isActive: boolean;
  falvourEn: string;
  falvourHi: string;
  falvourGu?: string;
  flavour_Sequence?: number;
  productNameHi: string;
  productNameGu?: string;
  hsnCode: string;
  facings?: number;
  defaultOrderQuantity: number;
  orderBoxBunch?: number;
  orderPatti?: number;
  orderPacket?: number;
}
